# Generated by Django 2.2.6 on 2019-11-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(blank=True, max_length=100)),
                ('book_publisher', models.CharField(blank=True, max_length=30, null=True)),
                ('book_ISBN', models.CharField(blank=True, max_length=50, null=True)),
                ('book_x_position', models.FloatField(null=True)),
                ('book_y_position', models.FloatField(null=True)),
                ('book_claim', models.CharField(max_length=50, null=True)),
                ('book_image_in_shelf', models.FileField(null=True, upload_to='files/')),
            ],
        ),
    ]
